# Generated by Django 3.2.8 on 2022-05-10 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('events', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_start', models.IntegerField()),
                ('event_end', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_owner', to='calendar.user')),
                ('shared_users', models.ManyToManyField(related_name='shared_events', to='calendar.User')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_event', to='calendar.user')),
            ],
        ),
    ]
