# Generated by Django 3.2.8 on 2022-05-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_start',
            new_name='start_date',
        ),
    ]
