# Generated by Django 3.2.8 on 2022-05-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0002_auto_20220510_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='events',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='gmail',
            field=models.EmailField(max_length=254),
        ),
    ]
