# Generated by Django 3.2.8 on 2022-05-11 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0003_auto_20220510_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='events',
        ),
        migrations.AlterField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calendar.user'),
        ),
    ]
