# Generated by Django 3.2.8 on 2022-05-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0004_auto_20220511_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
