# Generated by Django 3.2.8 on 2022-05-14 04:34

import calendar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0006_alter_event_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('users', models.JSONField(verbose_name=calendar.models.User)),
            ],
        ),
    ]
