# Generated by Django 3.2.8 on 2022-05-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0007_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.JSONField(default=dict),
        ),
    ]
